### ISSUE TITLE
BUG: codecov tries to upload even when not asked to

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/github-actions-workflows#109]
Not all the jobs in `astropy` CI matrix compute coverage:

https://github.com/astropy/astropy/blob/92a3af78b409543aa85c8d82de17e81062347284/.github/workflows/ci_workflows.yml#L81-L83

But using the template here, codecov is trying to upload coverage file that does not exist and then fails:

https://github.com/astropy/astropy/actions/runs/4245732365/jobs/7381634730

```
['error'] There was an error running the uploader: No coverage files located, please try use `-f`, or change the project root with `-R`
```

This check is insufficient:

https://github.com/OpenAstronomy/github-actions-workflows/blob/8b7048c550efb5471136d5a3b0782b291db839af/.github/workflows/tox.yml#L181

**Comment by ConorMacBride** [comment]
This is working as expected. `coverage: codecov` is defined for all jobs here: https://github.com/astropy/astropy/blob/92a3af78b409543aa85c8d82de17e81062347284/.github/workflows/ci_workflows.yml#L52

You can override your global setting and disable the upload for individual jobs by setting `coverage: ''`:
```yaml
        - name: Python 3.9 with all optional dependencies (MacOS X)
          macos: py39-test-alldeps
          posargs: --durations=50 --run-slow
          coverage: ''
```
