### ISSUE TITLE
Support running publish workflow on aarch64 runners

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/github-actions-workflows#227]
GitHub now has support for paid for aarch64 runners, which means [passing labels to `runs-on:`](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/running-jobs-on-larger-runners#using-labels-to-control-where-jobs-are-run). I don't think there is a way we can do this at the moment, looks like we would need to customise the [`get_os` function](https://github.com/OpenAstronomy/github-actions-workflows/blob/main/tools/load_build_targets.py#L38)

**Comment by Cadair** [comment]
@ConorMacBride I don't suppose you have any quick input on this before I start fumbling around in the dark?

**Comment by ConorMacBride** [comment]
We could support something like this to modify the default image? Should just be a matter of updating `get_matrix_item` to extract the options depending on whether it receives a string or a dict.

```yaml
jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs test_package
      targets: |
        - linux
        - build: cp3?-manylinux_aarch64
          runs-on: ubuntu-latest-aarch64
        - cp3?-macosx_x86_64
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
```
https://github.com/OpenAstronomy/github-actions-workflows/blob/a0669d967924b07daa381e64cf7a601196cb9247/tools/load_build_targets.py#L68-L75
