### ISSUE TITLE
issue with using `tox-conda`

### ISSUE THREAD

**Issue by zacharyburnett** [OpenAstronomy/github-actions-workflows#277]
when using `conda: true` with `conda_deps` and `conda_channel` set in the `tox.ini`, I get the following error:
https://github.com/spacetelescope/wfc3tools/actions/runs/15071133917/job/42367498006#step:6:53
```
  error    libmamba Could not solve for environment specs
      The following package could not be installed
      └─ python =3.0x * does not exist (perhaps a typo or a missing channel).
  critical libmamba Could not solve for environment specs
```

here is the YAML:
```yaml
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      conda: true
      envs: |
        - linux: py311-xdist
        - linux: py312-xdist
        - macos: py312-xdist
        - linux: py3-cov-xdist
          coverage: codecov
```

From #123, we are using `${{ matrix.python_version }}`:
https://github.com/OpenAstronomy/github-actions-workflows/blob/4f79fc804865ace8d60d63770787abdac826834c/.github/workflows/tox.yml#L199

However, I can't find where `python_version` is being set as `3.0x`:
https://github.com/OpenAstronomy/github-actions-workflows/blob/4f79fc804865ace8d60d63770787abdac826834c/tools/tox_matrix.py#L128-L137

**Comment by zacharyburnett** [comment]
Oh! It works when I remove all extra toxenv flags:
```yaml
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      conda: true
      envs: |
        - linux: py311-xdist
        - linux: py312-xdist
        - macos: py312-xdist
```
