### ISSUE TITLE
BUG: 'Load tox environments' shows up in jobs when using the workflow

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/github-actions-workflows#285]
Consider this in spectra-cube (e.g. latest run on `master`): https://github.com/radio-astro-tools/spectral-cube/actions/runs/15632910971

```

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: build_docs
        - linux: py310-test-oldestdeps
        - linux: py310-test
        - linux: py310-test-casa
        - linux: py311-test
        - linux: py311-test-dev
        - linux: py311-test-noviz-cov
        - linux: py311-test-noviz-dev
        - linux: py311-test-viz
        - linux: py311-test-viz-noviz
        - linux: py312-test
        - linux: py313-test
        - linux: py313-test-viz-noviz-dev
        - macos: py310-test-noviz
        - macos: py313-test-viz-noviz-dev
        - windows: py311-test-viz
        - windows: py313-test-viz-noviz-dev
```

Yet we have an extra, `Load tox environments` job, too.

cc @astrofrog
