### ISSUE TITLE
DOC: Working example of upload_to_pypi tag customization

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/github-actions-workflows#31]
It is explained in README that it can be customized but would be nice to have an example on how to drop the leading "v". Some packages tag `X.Y.Z` instead of `vX.Y.Z`. Thanks!

https://github.com/OpenAstronomy/github-actions-workflows/blob/ce411ebef92d6048328bee7486f0e2c8de1bece4/.github/workflows/publish_pure_python.yml#L21-L24

cc @tepickering

**Comment by Cadair** [comment]
>  Some packages tag X.Y.Z instead of vX.Y.Z

more fool them :stuck_out_tongue:

**Comment by pllim** [comment]
@Cadair , what do you mean? Please clarify.

**Comment by Cadair** [comment]
I was just joking that they should tag with a v ;)

**Comment by pllim** [comment]
Har har... _awkward silence_ ;)

**Comment by astrofrog** [comment]
I haven't tested but probably just setting the option to refs/tags/ instead of refs/tags/v might work?

**Comment by pllim** [comment]
Like this?
```yaml
jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      upload_to_pypi: refs/tags/
```
