### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by EwoutH** [OpenAstronomy/github-actions-workflows#53]
Python 3.11 is [now in beta](https://blog.python.org/2022/05/python-3110b1-is-now-available.html) and feature stable. It would be nice if Python 3.11 would be supported in this workflow!

**Comment by Cadair** [comment]
I think the main complexity there is that it would mean the workflow has to install python 3.11 where as at the moment we rely on actions to provide us the Python installs for the various versions.

Do you know if there is an action which provides pre-release Python we could use?

**Comment by EwoutH** [comment]
Would the regular [setup-python](https://github.com/actions/setup-python) work?
```
- uses: actions/setup-python@v3
  with:
    python-version: "3.11-dev"
```

**Comment by Cadair** [comment]
oh huh, well we are already using that.

**Comment by Cadair** [comment]
I guess this then becomes a question of parsing out the python version string from the tox env and appending `-dev`?

**Comment by ConorMacBride** [comment]
Which workflow of the workflows would you like to support Python 3.11? (`publish.yml`, `publish_pure_python.yml` or `tox.yml`)

In the tox workflow (`tox.yml`) it should work if you do:
```yaml
uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
with:
  envs: |
    - linux: toxenvname
      default_python: '3.11-dev'
```

Although currently if the `toxenvname` was `py311-toxenvname`, `'3.11'` would be passed to `actions/setup-python`, which may not exist yet. (Python specified in the tox envname overrides the `default_python` input.)

We should probably change this to the following, where `python-version` overrides the version specified in the `toxenvname`:
```yaml
uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
with:
  envs: |
    - linux: toxenvname
      python-version: '3.11-dev'
```

If it's for supporting Python 3.11 when building and testing sdists and pure Python wheels (`publish_pure_python.yml`), we have an existing issue https://github.com/OpenAstronomy/github-actions-workflows/issues/45

Supporting Python 3.11 on the compiled publishing workflow (`publish.yml`) is dependant on what cibuildwheel supports: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip
