### ISSUE TITLE
Reference the reusable workflow repo inside the workflow

### ISSUE THREAD

**Issue by ConorMacBride** [OpenAstronomy/github-actions-workflows#9]
To run the Python scripts within the reusable workflows we checkout the `main` branch of this repository. However, this means that if a PR updates a Python script the script that the PR CI tests is the version in the `main` branch and no the PR branch. Need to change the following in each workflow:

```yaml
- uses: actions/checkout@v2
  with:
    repository: 'OpenAstronomy/github-actions-workflows'
```
